name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test

    - name: Build binary
      run: make build
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.5.0